- name: install java for debian
  import_tasks: debian.yaml
  when: ansible_facts['os_family']|lower == 'debian'

- name: install java for rhel
  import_tasks: redhat.yaml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: set java_home if configured
  template:
    src: java_home.sh.j2
    dest: /etc/profile.d/java_home.sh
    mode: 0644
  when: java_home is defined and java_home
  become: yes