- name: get hosts facts
  hosts: all
  gather_facts: yes

- name: load ssh key
  hosts: localhost
  gather_facts: no
  vars:
    project: b2b marketplace
    deploy_environment: dev
  vars_files:
    - 'vars/{{ project | replace(" ", "_") }}_{{ deploy_environment }}_config.yaml'
  tasks:
    - name: kill running ssh agent
      shell: ps aux | grep [s]sh | awk '{print $2}' | xargs sudo kill -15
      become: yes
    - name: start ssh agent
      shell: |
        eval $(ssh-agent -s) > /dev/null
        echo '{"SSH_AUTH_SOCK":"'$SSH_AUTH_SOCK'","SSH_AGENT_PID":"'$SSH_AGENT_PID'"}'
      register: env_vars_stdout
    - name: store environment variables
      set_fact:
        env_vars: '{{ env_vars_stdout.stdout }}'
    - name: add ssh key
      shell: ssh-add '{{ code.repo_private_key }}'
      environment: '{{ env_vars }}'

- name: fetch project codes
  hosts: build_server
  gather_facts: no
  vars:
    project: b2b marketplace
    deploy_environment: dev
    ansible_ssh_common_args: '-o IdentityAgent={{ hostvars["localhost"]["env_vars"]["SSH_AUTH_SOCK"] }}'
  vars_files:
    - 'vars/{{ project | replace(" ", "_") }}_{{ deploy_environment }}_config.yaml'
  tasks:
    - name: init server environment
      include_role:
        name: init_server_environment
    - name: init workspace
      import_tasks: tasks/init_workspace.yaml

- name: set up db server
  hosts: db_servers
  gather_facts: no
  vars:
    project: b2b marketplace
    deploy_environment: dev
  vars_files:
    - 'vars/{{ project | replace(" ", "_") }}_{{ deploy_environment }}_config.yaml'
  tasks:
    - name: init server environment
      include_role:
        name: init_server_environment
    - name: build postgresql
      include_role:
        name: build_postgresql
    - name: initialize postgresql database
      import_tasks: tasks/initialize_postgresql_database.yaml

- name: build project codes
  hosts: build_server
  gather_facts: no
  vars:
    project: b2b marketplace
    deploy_environment: dev
    virtualenv: '{{ hostvars[inventory_hostname].ansible_env.HOME }}/.virtualenvs/{{ project | replace(" ", "-") }}-{{ deploy_environment }}-env'
  vars_files:
    - 'vars/{{ project | replace(" ", "_") }}_{{ deploy_environment }}_config.yaml'
  tasks:
    - name: init server environment
      include_role:
        name: init_server_environment
    - name: create python environment
      include_role:
        name: create_python_environment
    - name: install docker
      include_role:
        name: install_docker
    - name: build docker
      block:
      - name: set up docker registry
        import_role:
          name: set_up_docker_registry
      - name: build docker image
        import_tasks: tasks/build_docker_image.yaml
      vars:
        ansible_python_interpreter: '{{ virtualenv }}/bin/python3'
      environment:
        PATH: '{{ virtualenv }}/bin:{{ hostvars[inventory_hostname].ansible_env.PATH }}'


- name: set up app server
  hosts: app_servers
  gather_facts: no
  vars:
    project: b2b marketplace
    deploy_environment: dev
  vars_files:
    - 'vars/{{ project | replace(" ", "_") }}_{{ deploy_environment }}_config.yaml'
  tasks:
    - name: init server environment
      include_role:
        name: init_server_environment
    - name: install docker
      include_role:
        name: install_docker
    - name: set up app container
      import_tasks: tasks/set_up_app_container.yaml