- name: allow outside connect postgresql by password
  blockinfile:
    path: /etc/postgresql/12/main/pg_hba.conf
    marker: '# {mark} ANSIBLE MANAGED BLOCK'
    insertafter: '# IPv4 local connections:'
    block: |
      host    all    all    0.0.0.0/0    md5
    state: present
  notify: "restart {{ ansible_facts['os_family']|lower }} postgresql"
  become: yes

- name: allow outside connection
  blockinfile:
    path: /etc/postgresql/12/main/postgresql.conf
    marker: '# {mark} ANSIBLE MANAGED BLOCK'
    insertafter: '# - Connection Settings -'
    block: |
      listen_addresses = '*'
    state: present
  notify: "restart {{ ansible_facts['os_family']|lower }} postgresql"
  become: yes

- name: get the postgres listening port
  shell:
    cmd: netstat -plunt | grep postgres | awk '{print $4}' | sed -e 's/.*://' | uniq
  become: yes
  register: command_output

- name: set the postgres listening port
  set_fact:
    postgres_default_port: '{{ command_output.stdout }}'
  when: command_output is defined and command_output.stdout is defined and command_output.stdout != ''

- name: change postgresql port
  community.postgresql.postgresql_set:
    port: '{{ postgres_default_port }}'
    name: port
    value: '{{ db_port }}'
  notify: "restart {{ ansible_facts['os_family']|lower }} postgresql"
  become: yes
  become_user: postgres

- name: set up firewall
  include_role:
    name: set_up_ufw
  vars:
    enable_service: postgresql
    enable_port: '{{ db_port }}'