- name: install required repos for centos
  yum:
    name:
      - centos-release-scl-rh
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
  become: yes
  when:
    - ansible_distribution|lower == 'centos'

- name: install required dependencies for redhat
  block:
    - name: enable redhat repository
      community.general.rhsm_repository:
        name:
          - rhel-7-server-devtools-rpms
          - rhel-server-rhscl-7-rpms
        state: enabled
      become: yes
    - name: install required packages for redhat
      yum:
        name:
          - devtoolset-8
          - llvm-toolset-7.0
          - http://mirror.centos.org/centos/7/os/x86_64/Packages/libedit-devel-3.0-12.20121213cvs.el7.x86_64.rpm
        state: present
      become: yes
  when:
    - ansible_distribution|lower == 'redhat'

- name: install required packages
  yum:
    name:
      - net-tools
      - python-psycopg2
    state: present
  become: yes

- name: install postgresql 12 repository
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present
  become: yes

- name: install postgresql 12
  yum:
    name:
      - postgresql12-server
      - postgresql12-contrib
      - postgresql12-devel
    state: present
  become: yes

- name: initialize the cluster
  command: /usr/pgsql-12/bin/postgresql-12-setup initdb
  register: result
  become: yes
  failed_when:
    - result.rc != 0
    - '"Data directory is not empty" not in result.stdout'

- name: ensure the postgresql service is running
  service:
    name: postgresql-12
    state: started
    enabled: yes
  become: yes