- name: install postgresql for rhel
  import_tasks: install_postgresql_redhat.yaml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: install postgresql for debian
  import_tasks: install_postgresql_debian.yaml
  when: ansible_facts['os_family']|lower == 'debian'

- name: config postgresql connection for rhel
  import_tasks: config_connection_redhat.yaml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: config postgresql connection for debian
  import_tasks: config_connection_debian.yaml
  when: ansible_facts['os_family']|lower == 'debian'

- name: restart postgresql
  meta: flush_handlers

- name: initialize postgresql database
  import_tasks: tasks/initialize_postgresql_database.yaml

- name: create users
  include_tasks: create_user.yaml
  loop: '{{ db_user }}'
  loop_control:
    loop_var: account

- name: save postgresql login info to file
  import_tasks: save_to_file.yaml