---
- name: generate dockerfile
  template:
    src: Dockerfile.j2
    dest: '{{ code.location }}/Dockerfile'
    mode: 0644
    force: yes

- name: override the app properties
  template:
    src: application.properties.j2
    dest: '{{ code.location }}/src/main/resources/application-{{ deploy_environment }}.properties'
    force: yes

- name: build docker image

  block:
  - name: log into private registry
    community.docker.docker_login:
      registry_url: 127.0.0.1:443
      username: '{{ registry_user }}'
      password: '{{ registry_password }}'
      reauthorize: yes
  - name: push docker image to private registry
    community.docker.docker_image:
      name: '{{ project | replace(" ", "-") }}'
      tag: '{{ deploy_environment }}'
      build:
        path: '{{ code.location }}'
      source: build
      state: present
      force_source: yes
      force_tag: yes
      repository: '127.0.0.1:443/{{ project | replace(" ", "-") }}'
      push: yes

  always:
  - name: log out private registry
    community.docker.docker_login:
      registry_url: 127.0.0.1:443
      state: absent