---
- name: import postgresql credential
  include_vars:
    file: '/tmp/{{ hostvars[groups[deploy_environment + "_db_servers"][0]].ansible_host | default("") }}_postgresql_database_config.yaml'
    name: postgresql_credential

- name: format to accounts dict
  set_fact:
    postgresql_accounts: "{{ postgresql_accounts|default({}) | combine( {item.name: item.password} ) }}"
  loop:
    '{{ postgresql_credential.postgresql.user }}'

- name: set the postgres passwords
  set_fact:
    { 'postgresql_{{ item }}_password': '{{ postgresql_accounts[ [project|replace(" ", "_"), item, deploy_environment]|join("_") ] }}' }
  loop:
    '{{ code | selectattr("name", "defined") | map(attribute="name") | list }}'