---
- name: upload database initialize scripts to db server
  ansible.posix.synchronize:
    src: '/tmp/b2b_marketplace_code/db/'
    dest: '/tmp/postgresql_scripts/'
    mode: push
    delete: yes
    recursive: yes
  delegate_to: '{{groups["build_server"][0]}}'

- name: remove exist databases
  community.postgresql.postgresql_db:
    name: '{{ item }}'
    port: '{{ postgresql.port }}'
    state: absent
  become: yes
  become_user: postgres
  loop:
    - b2b_config
    - b2b_marketplace
    - quartz

- name: initialize cache db
  command: 'psql --file=/tmp/postgresql_scripts/cache_db_ddl.sql --port={{ postgresql.port }}'
  become: yes
  become_user: postgres

- name: initialize config db
  command: 'psql --file=/tmp/postgresql_scripts/config_db_ddl.sql --port={{ postgresql.port }}'
  become: yes
  become_user: postgres

- name: initialize quartz db
  command: 'psql --file=/tmp/postgresql_scripts/quartz_postgre_init.sql --port={{ postgresql.port }}'
  become: yes
  become_user: postgres

- name: ensure user has the access, step 1
  community.postgresql.postgresql_privs:
    db: '{{ item }}'
    port: '{{ postgresql.port }}'
    role: '{{ postgresql.user }}'
    objs: ALL_DEFAULT
    privs: ALL
    type: default_privs
    grant_option: yes
  become: yes
  become_user: postgres
  loop:
    - b2b_config
    - b2b_marketplace
    - quartz

- name: ensure user has the access, step 2
  community.postgresql.postgresql_privs:
    db: '{{ item }}'
    port: '{{ postgresql.port }}'
    role: '{{ postgresql.user }}'
    objs: ALL_IN_SCHEMA
    type: table
    privs: SELECT,INSERT,UPDATE,DELETE,TRIGGER
  become: yes
  become_user: postgres
  loop:
    - b2b_config
    - b2b_marketplace
    - quartz

- name: ensure user has the access, step 3
  community.postgresql.postgresql_privs:
    db: '{{ item }}'
    port: '{{ postgresql.port }}'
    role: '{{ postgresql.user }}'
    objs: ALL_IN_SCHEMA
    type: sequence
    privs: SELECT,UPDATE,USAGE
  become: yes
  become_user: postgres
  loop:
    - b2b_config
    - b2b_marketplace
    - quartz