- name: remove exist codes files directory
  file:
    path: '{{ component.location }}'
    state: absent
  become: yes

- name: git checkout codes
  git:
    repo: '{{ component.repo }}'
    depth: 1
    version: '{{ component.branch }}'
    dest: '{{ component.location }}'
    accept_hostkey: yes
    force: yes

- name: remove useless files
  file:
    path: '{{ component.location }}/.git'
    state: absent