- name: remove exist codes files directory
  file:
    path: '{{ code_path }}'
    state: absent
  delegate_to: 127.0.0.1

- name: git checkout codes
  git:
    repo: '{{ code_repo }}'
    depth: 1
    version: develop
    dest: '{{ code_path }}'
    key_file: '{{ code_repo_key }}'
    accept_hostkey: yes
    force: yes
  delegate_to: 127.0.0.1

- name: remove useless files
  file:
    path: '{{ code_path }}/.git'
    state: absent
  delegate_to: 127.0.0.1