- name: remove exist codes files directory
  file:
    path: '{{ code_path }}'
    state: absent

- name: git checkout codes
  git:
    repo: '{{ code_repo }}'
    depth: 1
    version: develop
    dest: '{{ code_path }}'
    accept_hostkey: yes
    force: yes

- name: remove useless files
  file:
    path: '{{ code_path }}/.git'
    state: absent