- name: remove exist codes files directory
  file:
    path: '{{ code.path }}'
    state: absent

- name: git checkout codes
  git:
    repo: '{{ code.repo }}'
    depth: 1
    version: develop
    dest: '{{ code.path }}'
    accept_hostkey: yes
    force: yes

- name: remove useless files
  file:
    path: '{{ code.path }}/.git'
    state: absent