---
- name: copy codes files to tmp path
  ansible.posix.synchronize:
    src: '/tmp/b2b_marketplace_code/db/'
    dest: '/tmp/postgresql_scripts/'
    mode: push
    delete: yes
    recursive: yes
  vars:
    ansible_python_interpreter: '/usr/bin/python3'
  delegate_to: '{{groups["build_server"][0]}}'

- name: remove exist databases
  community.postgresql.postgresql_db:
    name: '{{ item }}'
    port: '{{ database_port }}'
    state: absent
  become: yes
  become_user: postgres
  loop:
    - b2b_config
    - b2b_marketplace
    - quartz

- name: initalize cache db
  command: 'psql --file=/tmp/postgresql_scripts/cache_db_ddl.sql --port={{ database_port }}'
  become: yes
  become_user: postgres

- name: initalize config db
  command: 'psql --file=/tmp/postgresql_scripts/config_db_ddl.sql --port={{ database_port }}'
  become: yes
  become_user: postgres

- name: initalize quartz db
  command: 'psql --file=/tmp/postgresql_scripts/quartz_postgre_init.sql --port={{ database_port }}'
  become: yes
  become_user: postgres

- name: ensure user has the access, step 1
  community.postgresql.postgresql_privs:
    db: '{{ item }}'
    port: '{{ database_port }}'
    role: '{{ database_user }}'
    objs: ALL_DEFAULT
    privs: ALL
    type: default_privs
    grant_option: yes
  become: yes
  become_user: postgres
  loop:
    - b2b_config
    - b2b_marketplace
    - quartz

- name: ensure user has the access, step 2
  community.postgresql.postgresql_privs:
    db: '{{ item }}'
    port: '{{ database_port }}'
    role: '{{ database_user }}'
    objs: ALL_IN_SCHEMA
    type: table
    privs: SELECT,INSERT,UPDATE,DELETE,TRIGGER
  become: yes
  become_user: postgres
  loop:
    - b2b_config
    - b2b_marketplace
    - quartz

- name: ensure user has the access, step 3
  community.postgresql.postgresql_privs:
    db: '{{ item }}'
    port: '{{ database_port }}'
    role: '{{ database_user }}'
    objs: ALL_IN_SCHEMA
    type: sequence
    privs: SELECT,UPDATE,USAGE
  become: yes
  become_user: postgres
  loop:
    - b2b_config
    - b2b_marketplace
    - quartz