---
- name: include docker registry credential
  include_vars:
    file: /tmp/docker_registry_credential.yaml

- name: upload certificate to app server
  ansible.posix.synchronize:
    src: '{{ hostvars[groups["build_server"][0]].registry_path | default("") }}/certs/docker.crt'
    dest: '/tmp/docker.crt'
    mode: push
    delete: yes
    recursive: yes
  delegate_to: '{{ groups["build_server"][0] }}'

- name: ensure storing certificate directory exists
  file:
    path: '/etc/docker/certs.d/{{ hostvars[groups["build_server"][0]].ansible_host }}:443/'
    state: directory
    mode: 0755
  become: yes
  register: certificate_directory

- name: move certificate to destination
  copy:
    src: '/tmp/docker.crt'
    dest: '{{ certificate_directory.path }}/docker.crt'
    mode: 0644
    remote_src: yes
  become: yes

- name: pull docker image

  block:
    - name: log into private registry
      command: 'docker login {{ hostvars[groups["build_server"][0]].ansible_host }}:{{ docker_registry.port }} --username {{ docker_registry.user }} --password {{ docker_registry.password }}'
    - name: pull docker image from private registry
      command: 'docker pull {{ hostvars[groups["build_server"][0]].ansible_host }}:{{ docker_registry.port }}/{{ project | replace(" ", "-") }}:{{ deploy_environment }}'

  always:
    - name: log out private registry
      command: 'docker logout {{ hostvars[groups["build_server"][0]].ansible_host }}:{{ docker_registry.port }}'

- name: start docker container
  command: 'docker run --name={{ project | replace(" ", "-") }}-{{ deploy_environment }} -d -v ~/{{ project | replace(" ", "_") }}_{{ deploy_environment }}_logs:{{ code.log_path }} -p {{ docker.host_port }}:{{ docker.container_port }} --rm {{ hostvars[groups["build_server"][0]].ansible_host }}:{{ docker_registry.port }}/{{ project | replace(" ", "-") }}:{{ deploy_environment }}'