---
- name: include docker registry credential
  include_vars:
    file: '/tmp/{{ hostvars[groups[deploy_environment + "_build_server"][0]].ansible_host | default("") }}_docker_registry_credential.yaml'

- name: upload certificate to app server
  ansible.posix.synchronize:
    src: '{{ docker_registry.path }}/certs/docker.crt'
    dest: '/tmp/docker.crt'
    mode: push
    delete: yes
    recursive: yes
  delegate_to: '{{ groups[deploy_environment + "_build_server"][0] }}'
  vars:
    - ansible_user: '{{ synchronize_user | default(hostvars[inventory_hostname].ansible_user) }}'
    - ansible_password: '{{ synchronize_password | default(hostvars[inventory_hostname].ansible_password) }}'

- name: ensure storing certificate directory exists
  file:
    path: '/etc/docker/certs.d/{{ docker_registry.host }}:443/'
    state: directory
    mode: 0755
  become: yes
  register: certificate_directory

- name: move certificate to destination
  copy:
    src: '/tmp/docker.crt'
    dest: '{{ certificate_directory.path }}/docker.crt'
    mode: 0644
    remote_src: yes
  become: yes

- name: pull docker image

  block:
    - name: log into private registry
      command: 'docker login {{ docker_registry.host }}:{{ docker_registry.port }} --username {{ docker_registry.user }} --password {{ docker_registry.password }}'
    - name: pull docker image from private registry
      command: 'docker pull {{ docker_registry.host }}:{{ docker_registry.port }}/{{ project | replace(" ", "-") }}-{{ item.name }}:{{ deploy_environment }}'
      loop: '{{ code }}'

  always:
    - name: log out private registry
      command: 'docker logout {{ docker_registry.host }}:{{ docker_registry.port }}'

- name: create directories storing related files
  file:
    path: '{{ item.0.path }}/{{ item.1 }}'
    state: directory
    recurse: yes
    mode: '0755'
  loop: '{{ code|subelements("folder") }}'
  become: yes

- name: check for containers that actually exist
  shell: 'docker ps -aq --filter "name={{ project | replace(" ", "-") }}-{{ item.name }}-{{ deploy_environment }}"'
  loop: '{{ code }}'
  register: found_containers

- name: remove the containers found
  shell: 'docker stop {{ item.item }} && docker rm -f {{ item.item }}'
  loop: '{{ found_containers.results }}'
  when: item.stdout

- name: start app docker container
  command: 'docker run --name={{ project | replace(" ", "-") }}-{{ item.name }}-{{ deploy_environment }} -d -v {{ item.path }}:{{ item.path }} -p {{ docker.host_port }}:{{ docker.container_port }} --rm {{ docker_registry.host }}:{{ docker_registry.port }}/{{ project | replace(" ", "-") }}-{{ item.name }}:{{ deploy_environment }}'
  loop: '{{ code | selectattr("name","defined") | selectattr("name","equalto","app") | list }}'

- name: start housekeeping docker container
  command: 'docker run --name={{ project | replace(" ", "-") }}-{{ item.name }}-{{ deploy_environment }} -d -v {{ item.path }}:{{ item.path }} -v {{ item.path }}/housekeeping/cron:/var/log/cron -e CONTAINER_HOSTNAME={{ hostvars[inventory_hostname].ansible_host }} --rm {{ docker_registry.host }}:{{ docker_registry.port }}/{{ project | replace(" ", "-") }}-{{ item.name }}:{{ deploy_environment }}'
  loop: '{{ code | selectattr("name","defined") | selectattr("name","equalto","housekeeping") | list }}'