---
- name: uninstall docker old versions
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  become: yes

- name: ensure dependencies are installed
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
    state: present
  become: yes

- name: add docker apt key
  apt_key:
    url: '{{ docker_apt_gpg_key }}'
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key
  become: yes

- name: add docker repository
  apt_repository:
    repo: '{{ docker_apt_repository }}'
    state: present
    update_cache: true
  become: yes

- name: install docker engine
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  become: yes