---
- name: uninstall docker old versions
  yum:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    state: absent
  become: yes

- name: add docker gpg key
  rpm_key:
    key: '{{ docker_yum_gpg_key }}'
    state: present
  become: yes

- name: add docker ce repo
  get_url:
    url: '{{ docker_yum_repo_url }}'
    dest: '/etc/yum.repos.d/docker-ce.repo'
    owner: root
    group: root
    mode: 0644
  become: yes

- name: enable redhat repository
  community.general.rhsm_repository:
    name:
      - rhel-7-server-extras-rpms
    state: enabled
  become: yes
  when:
    - ansible_distribution|lower == 'redhat'

- name: install docker engine
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - container-selinux
    state: present
  become: yes