- name: permit traffic in public zone for specific service
  ansible.posix.firewalld:
    service: '{{ enable_service }}'
    permanent: yes
    state: enabled
    zone: public
  become: yes
  when: enable_service is defined
  vars:
    ansible_python_interpreter: '/usr/bin/python2'

- name: permit traffic in public zone for specific port
  ansible.posix.firewalld:
    port: '{{ enable_port }}/tcp'
    permanent: yes
    state: enabled
    zone: public
  become: yes
  when: enable_port is defined
  vars:
    ansible_python_interpreter: '/usr/bin/python2'

- name: reload firewalld
  systemd:
    name: firewalld
    state: reloaded
  become: yes