- name: permit traffic in public zone for specific service
  ansible.posix.firewalld:
    service: '{{ enable_service }}'
    permanent: yes
    state: enabled
    zone: public
  become: yes

- name: permit traffic in public zone for specific port
  ansible.posix.firewalld:
    port: '{{ enable_port }}/tcp'
    permanent: yes
    state: enabled
    zone: public
  become: yes

- name: reload firewalld
  systemd:
    name: firewalld
    state: reloaded
  become: yes