- name: check whether maven is already installed
  stat:
    path: '{{ maven_home_parent_directory }}/apache-maven-{{ maven_version }}'
  register: maven_installed

- name: download maven binaries
  get_url:
    url: '{{ maven_download_url }}'
    dest: '{{ maven_home_parent_directory }}/{{ maven_file_name }}'
  become: yes
  when: not maven_installed.stat.exists

- name: unarchive maven binaries
  unarchive:
    src: '{{ maven_home_parent_directory }}/{{ maven_file_name }}'
    dest: '{{ maven_home_parent_directory }}'
    remote_src: yes
  become: yes
  when: not maven_installed.stat.exists

- name: create symbolic links
  import_tasks: create_symbolic_links.yaml

- name: cleaning up downloaded files
  file:
    path: '{{ maven_home_parent_directory }}/{{ maven_file_name }}'
    state: absent
  become: yes