- name: upload ufw application profile for postgresql
  template:
    src: '{{ enable_service }}.j2'
    dest: '/etc/ufw/applications.d/{{ enable_service }}.ini'
    owner: root
    group: root
    mode: '0644'
    force: yes
  become: yes

- name: allow postgresql
  community.general.ufw:
    rule: allow
    name: '{{ item }}'
  become: yes
  loop:
    - OpenSSH
    - PostgreSQL

- name: enable ufw
  community.general.ufw:
    state: enabled
  become: yes