- name: update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 86400
  become: yes
  ignore_errors: yes

- name: update all packages
  apt:
    upgrade: dist
  become: yes

- name: install required packages
  apt:
    name:
      - sshpass
    state: present
  become: yes

- name: install python3 and related packages
  apt:
    name:
      - python3
      - python3-dev
      - python3-pip
      - python3-virtualenv
      - python3-wheel
    state: present
  become: yes