- name: update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 86400
  become: yes
  ignore_errors: yes

- name: update all packages
  apt:
    upgrade: dist
  become: yes

- name: install required packages
  apt:
    name:
      - sshpass
    state: present
  become: yes