- name: update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 86400
  become: yes
  ignore_errors: yes

- name: update all packages
  apt:
    upgrade: dist
  become: yes

- name: install required packages
  apt:
    name:
      - sshpass
    state: present
  become: yes

- name: check if python symbolic link exists
  stat:
    path: '/usr/bin/python'
  register: python_link

- name: check if python3 exists
  stat:
    path: '/usr/bin/python3'
  register: python3_link

- name: create python symbolic link
  file:
    src: '/usr/bin/python3'
    dest: '/usr/bin/python'
    owner: root
    group: root
    mode: '0777'
    state: link
  when: (not python_link.stat.exists) and python3_link.stat.exists
  become: yes