- name: init server environment for debian
  import_tasks: debian.yaml
  when: ansible_facts['os_family']|lower == 'debian'

- name: init server environment for rhel
  import_tasks: redhat.yaml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: check motd banner messages exists
  stat:
    path: /tmp/motd
  register: motd_exist
  delegate_to: localhost
  when: use_motd_banner

- name: update motd banner messages
  copy:
    src: /tmp/motd
    dest: /etc/
    owner: root
    group: root
    mode: '0644'
    backup: yes
  become: yes
  when: motd_exist is defined and motd_exist.stat is defined and motd_exist.stat.exists