---
docker_repo_url: https://download.docker.com/linux
docker_apt_arch: amd64
docker_apt_release_channel: stable
docker_apt_gpg_key: '{{ docker_repo_url }}/{{ ansible_distribution | lower }}/gpg'
docker_apt_repository: 'deb [arch={{ docker_apt_arch }}] {{ docker_repo_url }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}'
docker_yum_gpg_key: '{{ docker_repo_url }}/centos/gpg'
docker_yum_repo_url: '{{ docker_repo_url }}/{{ (ansible_distribution == "Fedora") | ternary("fedora","centos") }}/docker-ce.repo'
docker_users:
  - boxing