---
- name: install python3 for debian
  import_tasks: debian.yaml
  when: ansible_facts['os_family']|lower == 'debian'

- name: install python3 for rhel
  import_tasks: redhat.yaml
  when: ansible_facts['os_family']|lower == 'redhat'